name: app_smart_milk
description: "A new Flutter project."
publish_to: 'none' # Remova esta linha se quiser publicar no pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.8
  mqtt_client: ^10.8.0
  qr_code_scanner_plus: ^2.0.10+1
  flutter_image_compress: ^2.4.0
  image_picker: ^1.1.2
  intl: ^0.18.1
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/images/
